events {
    worker_connections 128;
}

http {
    upstream api {
        server api:5000;
    }

    upstream healthcheck {
        server healthcheck:9090;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://api;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /dashboard/health {
            proxy_pass http://healthcheck/health;
            proxy_set_header Host $host;
        }
    }
}
